"""Create disease and ethnicity distribution plots from a PRISM CSV file."""

import argparse
import itertools
import re
import sys
from pathlib import Path

# Keep generated bytecode caches out of the source tree.
sys.dont_write_bytecode = True
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.ticker import MaxNLocator

# ==============================================================
# 1. RUN-BUTTON SETTINGS
# Edit these three values, then click Run/Play in your editor.
# No terminal arguments are required.
# ==============================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Use an absolute path or a path relative to the PRISM project directory.
INPUT_FILE = "data/master_dataset.csv"  # put CSV file here
OUTPUT_FOLDER = "stats_results/data_distribution"  # plots are saved here
TOP_N = 20  # number of diseases in the top-diseases graph
ETHNICITIES = ("European", "Asian", "African", "Other")


def parse_args():
    parser = argparse.ArgumentParser(description="Plot disease and ethnicity distributions from a CSV file.")
    parser.add_argument(
        "--input-csv", type=Path, help="CSV input. Overrides INPUT_FILE configured near the top of this file."
    )
    parser.add_argument(
        "--output-dir", type=Path, help="Plot output directory. Overrides OUTPUT_FOLDER configured above."
    )
    parser.add_argument("--top-n", type=int, help="Number of diseases shown. Overrides TOP_N configured above.")
    return parser.parse_args()


def resolve_path(path):
    path = Path(path).expanduser()
    return path if path.is_absolute() else PROJECT_ROOT / path


def load_data(input_path):
    input_path = resolve_path(input_path)
    if input_path.suffix.lower() != ".csv":
        raise ValueError(f"Input must be a CSV file: {input_path}")
    if not input_path.is_file():
        raise FileNotFoundError(f"Input CSV does not exist: {input_path}")
    data = pd.read_csv(input_path)
    required = {"disease", "ethnicity_category"}
    missing = required.difference(data.columns)
    if missing:
        raise ValueError("Input CSV is missing required column(s): " + ", ".join(sorted(missing)))
    data = data.copy()
    data["disease"] = data["disease"].fillna("Unknown disease").astype(str)
    data["ethnicity_category"] = (
        data["ethnicity_category"]
        .fillna("Unknown")
        .astype(str)
        .str.strip()
        .replace(
            {
                "Others": "Other",
                "others": "Other",
                "other": "Other",
                "EUROPEAN": "European",
                "ASIAN": "Asian",
                "AFRICAN": "African",
            }
        )
    )
    return data, input_path


# =========================
# 2. Plotting helpers
# =========================

COLORS = {
    "navy": "#24364B",
    "teal": "#118A7E",
    "purple": "#6D5BD0",
    "gold": "#D59035",
    "grid": "#DDE5E2",
    "muted": "#687875",
}


def clean_disease_label(label, max_length=None):
    """Remove internal hash suffixes and optionally shorten long labels."""
    label = re.sub(r"__[0-9a-fA-F]+$", "", str(label)).strip()
    if max_length and len(label) > max_length:
        return label[: max_length - 1].rstrip() + "…"
    return label


def style_axis(axis, grid_axis="x"):
    axis.set_axisbelow(True)
    axis.grid(axis=grid_axis, color=COLORS["grid"], linewidth=0.7, alpha=0.8)
    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)
    axis.spines["left"].set_color(COLORS["grid"])
    axis.spines["bottom"].set_color(COLORS["grid"])
    axis.tick_params(colors=COLORS["muted"])


def add_bar_values(axis, bars, fontsize=8):
    padding = max((bar.get_width() for bar in bars), default=0) * 0.008
    for bar in bars:
        axis.text(
            bar.get_width() + padding,
            bar.get_y() + bar.get_height() / 2,
            f"{int(bar.get_width()):,}",
            va="center",
            ha="left",
            fontsize=fontsize,
            color=COLORS["muted"],
        )


def save_figure(figure, path, dpi=160):
    figure.savefig(path, dpi=dpi, bbox_inches="tight", facecolor="white")
    plt.close(figure)
    print(f"Saved: {path}")


# =========================
# 3. Requested bar charts
# =========================


def plot_all_diseases(disease_counts, output_dir):

    # Horizontal bars remain readable even when the file contains hundreds of
    # diseases. The largest group is placed at the top.
    display_counts = disease_counts.sort_values(ascending=True)
    height = max(10, len(display_counts) * 0.22)
    figure, axis = plt.subplots(figsize=(15, height))
    bars = axis.barh(
        [clean_disease_label(label, 72) for label in display_counts.index],
        display_counts.values,
        color=COLORS["navy"],
        edgecolor="none",
    )
    axis.set_title("Number of rows per disease", loc="left", fontsize=16, fontweight="bold", pad=14)
    axis.set_xlabel("Number of rows")
    axis.set_ylabel("Disease")
    axis.tick_params(axis="y", labelsize=5 if len(display_counts) > 100 else 8)
    axis.xaxis.set_major_locator(MaxNLocator(integer=True))
    style_axis(axis)
    if len(display_counts) <= 100:
        add_bar_values(axis, bars, fontsize=7)
    save_figure(figure, output_dir / "01_rows_per_disease.png", dpi=110)


def plot_top_diseases(disease_counts, output_dir, top_n):
    top_counts = disease_counts.head(top_n).sort_values(ascending=True)
    figure, axis = plt.subplots(figsize=(13, max(7, top_n * 0.42)))
    bars = axis.barh(
        [clean_disease_label(label, 58) for label in top_counts.index],
        top_counts.values,
        color=COLORS["teal"],
        edgecolor="none",
    )
    axis.set_title(f"Top {top_n} diseases by row count", loc="left", fontsize=16, fontweight="bold", pad=14)
    axis.set_xlabel("Number of rows")
    axis.set_ylabel("Disease")
    axis.xaxis.set_major_locator(MaxNLocator(integer=True))
    style_axis(axis)
    add_bar_values(axis, bars)
    save_figure(figure, output_dir / f"02_top_{top_n}_diseases.png")


def plot_ethnicities(ethnicity_counts, output_dir):
    display_counts = ethnicity_counts.sort_values(ascending=True)
    figure, axis = plt.subplots(figsize=(10, max(5, len(display_counts) * 0.65)))
    palette = [COLORS["purple"] if label != "Unknown" else "#9AA7A3" for label in display_counts.index]
    bars = axis.barh(display_counts.index, display_counts.values, color=palette)
    axis.set_title("Number of rows per ethnicity", loc="left", fontsize=16, fontweight="bold", pad=14)
    axis.set_xlabel("Number of rows")
    axis.set_ylabel("Ethnicity category")
    axis.xaxis.set_major_locator(MaxNLocator(integer=True))
    style_axis(axis)
    add_bar_values(axis, bars)
    save_figure(figure, output_dir / "03_rows_per_ethnicity.png")


# =========================
# 4. Pairwise ethnicity plots
# =========================


def build_ethnicity_disease_counts(data):
    counts = (
        data[data["ethnicity_category"].isin(ETHNICITIES)]
        .groupby(["disease", "ethnicity_category"])
        .size()
        .unstack(fill_value=0)
        .reindex(columns=ETHNICITIES, fill_value=0)
    )
    counts.index.name = "disease"
    return counts


def plot_ethnicity_pair(counts, ethnicity_x, ethnicity_y, output_dir):
    x = counts[ethnicity_x]
    y = counts[ethnicity_y]
    max_value = int(max(x.max(), y.max(), 1))
    limit = max_value * 1.08 + 1
    figure, axis = plt.subplots(figsize=(8.5, 7.5))
    sizes = 24 + np.sqrt(x + y) * 7
    axis.scatter(x, y, s=sizes, color=COLORS["teal"], alpha=0.62, edgecolors="white", linewidths=0.6)
    axis.plot([0, limit], [0, limit], linestyle="--", color="#AAB6B2", linewidth=1)

    # Label the five diseases with the most images across this pair. Every point
    # remains present; selective labels keep dense plots readable.
    top_labels = (x + y).nlargest(5).index
    for disease in top_labels:
        if x.loc[disease] == 0 and y.loc[disease] == 0:
            continue
        axis.annotate(
            clean_disease_label(disease, 34),
            (x.loc[disease], y.loc[disease]),
            xytext=(5, 5),
            textcoords="offset points",
            fontsize=7,
            color=COLORS["navy"],
        )
    axis.set_xlim(-limit * 0.015, limit)
    axis.set_ylim(-limit * 0.015, limit)
    axis.set_aspect("equal", adjustable="box")
    axis.set_xlabel(f"{ethnicity_x} images per disease")
    axis.set_ylabel(f"{ethnicity_y} images per disease")
    axis.set_title(
        f"Disease image counts: {ethnicity_x} vs {ethnicity_y}", loc="left", fontsize=15, fontweight="bold", pad=14
    )
    axis.text(
        0.99,
        0.02,
        f"Each point is one disease · n={len(counts):,}",
        transform=axis.transAxes,
        ha="right",
        va="bottom",
        fontsize=8,
        color=COLORS["muted"],
    )
    axis.xaxis.set_major_locator(MaxNLocator(integer=True))
    axis.yaxis.set_major_locator(MaxNLocator(integer=True))
    style_axis(axis, grid_axis="both")
    filename = f"04_scatter_{ethnicity_x.lower()}_vs_{ethnicity_y.lower()}.png"
    save_figure(figure, output_dir / filename)


# =========================
# 5. Run
# =========================


def main():
    args = parse_args()
    top_n = args.top_n if args.top_n is not None else TOP_N
    if top_n < 1:
        raise ValueError("--top-n must be at least 1.")
    configured_input = args.input_csv or INPUT_FILE
    if not configured_input:
        raise ValueError("No input configured. Set INPUT_FILE near the top of this script " "or provide --input-csv.")
    data, input_path = load_data(configured_input)
    output_dir = resolve_path(args.output_dir or OUTPUT_FOLDER)
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"Input: {input_path}")
    print(f"Rows: {len(data):,}")
    print(f"Diseases: {data['disease'].nunique():,}")
    print(f"Output: {output_dir}")
    disease_counts = data["disease"].value_counts().sort_values(ascending=False)
    ethnicity_counts = data["ethnicity_category"].value_counts().sort_values(ascending=False)
    ethnicity_disease_counts = build_ethnicity_disease_counts(data)

    # Save exact chart source values alongside the plots.
    disease_counts.rename("row_count").to_csv(output_dir / "disease_counts.csv")
    ethnicity_counts.rename("row_count").to_csv(output_dir / "ethnicity_counts.csv")
    ethnicity_disease_counts.to_csv(output_dir / "disease_counts_by_ethnicity.csv")
    plot_all_diseases(disease_counts, output_dir)
    plot_top_diseases(disease_counts, output_dir, top_n)
    plot_ethnicities(ethnicity_counts, output_dir)
    for ethnicity_x, ethnicity_y in itertools.combinations(ETHNICITIES, 2):
        plot_ethnicity_pair(ethnicity_disease_counts, ethnicity_x, ethnicity_y, output_dir)
    print("\nCreated 9 graphs and 3 supporting CSV files.")


if __name__ == "__main__":
    main()
